### ISSUE TITLE
Video Streaming support

### ISSUE THREAD

**Issue by renjithn** [leshkoapps/AVAssetResourceLoader#1]
This is a very cool project.
Just wanted to ask how difficult will it be to implement Video Streaming with Caching using AVAssetResourceLoader? Is it possible?

**Comment by everappz** [comment]
Yes it's possible. The most part of code is the same. The difference in AVPlayer initialization. You should add AVPlayerLayer as described here: https://developer.apple.com/library/ios/documentation/AudioVideo/Conceptual/AVFoundationPG/Articles/02_Playback.html#//apple_ref/doc/uid/TP40010188-CH3-SW2

**Comment by renjithn** [comment]
@leshkoapps Thanks for the reply. I ended up writing a custom class conforming to the AVAssetResourceLoaderDelegate protocol and it worked with my existing player. 
A suggestion to make this project more popular would be to have the stream end point more flexible,
As of now I feel this is centred around Yandex.

Thanks again. :)

**Comment by william9917** [comment]
on ne peux pas active sa desoler
